FROM python:3.14-slim

WORKDIR /workspace

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY tests/ ./tests/

CMD ["python", "-m", "unittest", "discover", "-s", "tests", "-v"]
